// <auto-generated />
using System;
using ArchivePortal.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ArchivePortal.Data.Migrations
{
    [DbContext(typeof(PipelineArchiveDbContext))]
    [Migration("20190506140830_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ArchivePortal.Core.PipelineArchive", b =>
                {
                    b.Property<long>("PipelineArchivesId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("Body");

                    b.Property<string>("BodyIntro");

                    b.Property<long>("CompressedSize");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<Guid>("InterchangeId");

                    b.Property<bool>("IsCompressed");

                    b.Property<Guid>("MessageId");

                    b.Property<string>("Property");

                    b.Property<string>("ReceiveLocation");

                    b.Property<string>("ReceivedFilename");

                    b.Property<string>("SendPort");

                    b.Property<long>("Size");

                    b.HasKey("PipelineArchivesId");

                    b.ToTable("tbl_PipelineArchives");
                });
#pragma warning restore 612, 618
        }
    }
}
